---
- name: install nginx package in system
  become: yes
  hosts: all
  tasks:
    - name: install nginx in ubuntu
      apt:
        update_cache: yes
        name: nginx
        state: absent
      when: ansible_distribution == 'Ubuntu' 
    - name: install nginx in ubuntu 
      dnf:
        name: nginx
        state: absent
      when: ansible_distribution == 'Amazon' 
